# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dfa1aa2adf2eb6988b3436e46a09200f070b932f8f95f565220ad220828766c8e2500ed7e8a54f05bcebe53b2822f52da545d88ddd3bf32350d35f94eecc402f

test:
  secret_key_base: 3b3bf095b94f5ef5d251849781d63a676ea487bed163676f8ea1b75be9f2621e7aca96df8313629aba67c641285473221839578d99437e6e5fc59c53b84f80f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
